//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskirli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLoginHistory
    {
        public int AccountId { get; set; }
        public System.DateTime Date { get; set; }
        public string Ip { get; set; }
        public Nullable<int> DeviceTypeId { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
    }
}
