//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskirli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountHistory
    {
        public int AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string street { get; set; }
        public string ZipCode { get; set; }
        public int PhoneNumberCountryCodeId { get; set; }
        public int PhoneNumber { get; set; }
        public string AppToken { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
    }
}
