//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskirli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InProcessRental
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal RentPricePerDay { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Item Item { get; set; }
        public virtual RentStatu RentStatu { get; set; }
    }
}
