//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskirli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemHistory
    {
        public int ItemId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> RenterId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public decimal RentPricePerDay { get; set; }
        public Nullable<int> CurrencyTypeId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
