//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskirli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRentArea
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> AreaEntityType { get; set; }
        public int AreaId { get; set; }
    
        public virtual AreaEntityType AreaEntityType1 { get; set; }
        public virtual Item Item { get; set; }
    }
}
